### PR TITLE
Add gulp-changed to prevent compiling of EVERY file every time.

### PR DESCRIPTION
**Pull request by fidgetwidget**
Also updated jade and gulp-notify to newer version.

### CODE REVIEW

**Comment by CREEATION** [comment]
Hello and thanks for your pull request!
What are those lines for in the package.json? `35-42` with `gitHead`, etc.?
I guess they are not supposed to be there?

**Comment by CREEATION** [comment]
@fidgetwidget ? :)

**Comment by CREEATION** [comment]
@fidgetwidget would be cool if you'd resolve the conflicts so I can merge this :)

**Comment by mastito03** [comment]
I think this conflict seems have been resolved after 755f22a9858622e898843e0cb3d12b7de48720e9

**Comment by fidgetwidget** [comment]
@CREEATION  wow, I really missed this - so sorry for not being responsive. I don't usually check notifications on github, and the email somehow completely slipped by me.

**Pull request merged**
